---
- name: ensure that gitlabot repository is present
  git:
    repo: 'https://github.com/saphirevert/gitlabot'
    dest: /srv/gitlabot
    version: "{{ git_current_branch }}"
    force: yes

- name: Copy secrets from keybase
  copy:
    src: /keybase/team/epfl_gitlabot/secrets.json
    dest: /srv/gitlabot/app/secrets.json

- name: Start docker container gitlabot
  docker_compose:
    project_src: /srv/gitlabot
    state: present
    build: yes
    recreate: always
    nocache: yes
    pull: yes
    files:
      - docker-compose-prod.yml
