version: "3"
services:
  node:
    image: "node"
    working_dir: "/gitlabot"
    volumes:
      - "./app:/gitlabot"
    expose:
      - "8081"
    restart: unless-stopped
    command: "npm run-script start"
